name: Auto Backup

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Push to backup branch
        run: |
          git config --global user.name "backup-bot"
          git config --global user.email "backup@github.com"

          git fetch origin
          git checkout -B backup
          git merge origin/main --no-edit

          git push origin backup --force
